### ISSUE TITLE
Test script fails on dtype='f16'

### ISSUE THREAD

**Issue by AstroMike** [esheldon/pymangle#26]
Not quite sure what's going on here .... I thought f16 _was_ a valid dtype? But my python seems to complain

```
> python -V
Python 3.9.13
> pip install pymangle
...
Successfully installed pymangle-0.9.2
> python -c 'import pymangle; pymangle.test.test()'
testExtraLines (pymangle.test.TestRead)
extra line at the end ... ok
testMinimalNonStandard (pymangle.test.TestRead)
absolutely minimal header, non standard ... ok
testMinimalNonStandardNopolycount (pymangle.test.TestRead)
absolutely minimal header, non standard, without even ... ok
testNopixel (pymangle.test.TestRead)
standard header with no pixels in the header ... ERROR
testStandardPixelized (pymangle.test.TestRead)
standard header with pixel ... ok
testStandardUnpixelized (pymangle.test.TestRead)
a basic mask with standard header, no pixelization ... ok
testWeightOnly (pymangle.test.TestRead)
standard header with only weight in addition to caps ... ok

======================================================================
ERROR: testNopixel (pymangle.test.TestRead)
standard header with no pixels in the header
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mjhudson/opt/anaconda3/lib/python3.9/site-packages/pymangle/test.py", line 120, in testNopixel
    assert np.all(m.contains(ra, dec))
  File "/Users/mjhudson/opt/anaconda3/lib/python3.9/site-packages/pymangle/mangle.py", line 149, in contains
    ra = array(ra, ndmin=1, dtype='f16', copy=False, order='C')
TypeError: data type 'f16' not understood

----------------------------------------------------------------------
Ran 7 tests in 0.042s

```

**Comment by erykoff** [comment]
I assume you are running on Apple Silicon?  `pymangle` (and `mangle`) requires true `long double` support (80 bit on x86), while Apple Silicon has `long double` map onto 64-bit `double`.

**Comment by AstroMike** [comment]
Hi Eli

Yes, Apple M1.

So this sounds fatal (... at least in the current version)?

**Comment by erykoff** [comment]
It's an arm limitation, and I don't know of anything on the roadmap to make it work.  I have tried hacking together software support for long double and failed completely.  As for pymangle, mangle itself does require this, so I simply don't have an answer except to suggest moving to something other than mangle.

**Comment by AstroMike** [comment]
OK, thanks for the quick update. We will find an x86 machine.
